# Generated by Django 4.2.11 on 2024-04-16 04:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.TextField(max_length=8, unique=True)),
                ("idPhoto", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="sfgsd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="myapp.person",
                    ),
                ),
                (
                    "idDriver",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("penalRecord", models.FileField(upload_to="")),
                ("policeRecord", models.FileField(upload_to="")),
                ("driverlicencePhoto", models.FileField(upload_to="")),
            ],
            bases=("myapp.person",),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "plate",
                    models.TextField(max_length=7, primary_key=True, serialize=False),
                ),
                ("year", models.DateField()),
                ("brand", models.TextField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Blanco", "Blanco"),
                            ("Negro", "Negro"),
                            ("Gris", "Gris"),
                            ("Plateado", "Plateado"),
                            ("Azul", "Azul"),
                            ("Rojo", "Rojo"),
                            ("Blanco perlado", "Blanco perlado"),
                            ("Negro metálico", "Negro metálico"),
                            ("Gris oscuro", "Gris oscuro"),
                            ("Plateado metálico", "Plateado metálico"),
                            ("Azul oscuro", "Azul oscuro"),
                            ("Rojo metálico", "Rojo metálico"),
                            ("Blanco sólido", "Blanco sólido"),
                            ("Negro sólido", "Negro sólido"),
                            ("Gris claro", "Gris claro"),
                            ("Plateado brillante", "Plateado brillante"),
                            ("Azul claro", "Azul claro"),
                            ("Rojo brillante", "Rojo brillante"),
                        ],
                        max_length=255,
                    ),
                ),
                ("vinNumber", models.TextField(max_length=8)),
                ("engineNumber", models.TextField(max_length=17)),
                ("purchaseDate", models.DateField()),
                ("purchaseKilometer", models.IntegerField()),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="myapp.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Replacements",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("value", models.IntegerField()),
                ("commet", models.TextField(max_length=250)),
                (
                    "owner_relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.person"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.state",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="myapp.person",
                    ),
                ),
                (
                    "driver_relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.driver"
                    ),
                ),
            ],
            bases=("myapp.person",),
        ),
        migrations.AddField(
            model_name="driver",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deliveryDocument", models.FileField(upload_to="")),
                ("deliveryVideo", models.FileField(upload_to="")),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.vehicle",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Atlántida", "Atlántida"),
                            ("Choluteca", "Choluteca"),
                            ("Colón", "Colón"),
                            ("Comayagua", "Comayagua"),
                            ("Copán", "Copán"),
                            ("Cortés", "Cortés"),
                            ("El Paraíso", "El Paraíso"),
                            ("Francisco Morazán", "Francisco Morazán"),
                            ("Gracias a Dios", "Gracias a Dios"),
                            ("Intibucá", "Intibucá"),
                            ("Islas de la Bahía", "Islas de la Bahía"),
                            ("La Paz", "La Paz"),
                            ("Lempira", "Lempira"),
                            ("Ocotepeque", "Ocotepeque"),
                            ("Olancho", "Olancho"),
                            ("Santa Bárbara", "Santa Bárbara"),
                            ("Valle", "Valle"),
                            ("Yoro", "Yoro"),
                        ],
                        max_length=255,
                    ),
                ),
                ("street", models.TextField()),
                ("houseNumber", models.IntegerField()),
                ("creationDate", models.DateTimeField(auto_now_add=True)),
                (
                    "driverId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.driver"
                    ),
                ),
            ],
        ),
    ]
